parameters:
  app.log_file_path: '/var/www/source/log/oe_examples_module.log'

imports:
  - { resource: src/Greeting/services.yaml }
  - { resource: src/Logging/services.yaml }
  - { resource: src/ProductVote/services.yaml }
  - { resource: src/Settings/services.yaml }
  - { resource: src/Tracker/services.yaml }

services:

  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true