services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\Greeting\Infrastructure\Factory\UserModelFactoryInterface:
    class: OxidEsales\ExamplesModule\Greeting\Infrastructure\Factory\UserModelFactory
