imports:
  - { resource: Infrastructure/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\ExamplesModule\Tracker\Service\TrackerServiceInterface:
    class: OxidEsales\ExamplesModule\Tracker\Service\TrackerService
    public: true

  OxidEsales\ExamplesModule\Tracker\Subscriber\BeforeModelUpdate:
    class: OxidEsales\ExamplesModule\Tracker\Subscriber\BeforeModelUpdate
    tags: [ 'kernel.event_subscriber' ]