services:
  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Request: '@=service("OxidEsales\\ExamplesModule\\Core\\Registry").getRequest()'
      OxidEsales\Eshop\Core\Language: '@=service("OxidEsales\\ExamplesModule\\Core\\Registry").getLang()'

  OxidEsales\ExamplesModule\Greeting\Repository\GreetingRepositoryInterface:
    class: OxidEsales\ExamplesModule\Greeting\Repository\GreetingRepository
    public: true

  OxidEsales\ExamplesModule\Greeting\Service\GreetingMessageServiceInterface:
    class: OxidEsales\ExamplesModule\Greeting\Service\GreetingMessageService
    public: true

  OxidEsales\ExamplesModule\Greeting\Infrastructure\UserModelFactoryInterface:
    class: OxidEsales\ExamplesModule\Greeting\Infrastructure\UserModelFactory

  OxidEsales\ExamplesModule\Greeting\Service\UserServiceInterface:
    class: OxidEsales\ExamplesModule\Greeting\Service\UserService
    public: true

  OxidEsales\ExamplesModule\Greeting\Transput\AdminGreetingRequestInterface:
    class: OxidEsales\ExamplesModule\Greeting\Transput\AdminGreetingRequest
    public: true

  OxidEsales\ExamplesModule\Greeting\Controller\GreetingController:
    public: true
    tags:
      - { name: 'oxid.view_controller', controller_key: 'oe_examples_module-greeting-controller' }

  OxidEsales\ExamplesModule\Greeting\Controller\Admin\GreetingAdminController:
    public: true
    tags:
      - { name: 'oxid.view_controller', controller_key: 'oe_examples_module-greeting-admin-controller' }
